version: '3.8'
services:
    php-apache-environment:
        container_name: php-apache
        build:
            context: ./php
            dockerfile: Dockerfile
        depends_on:
            - mysql
        volumes:
            - ./app:/var/www/html/
        ports:
            - 80:80
            - 443:443
    mysql:
        container_name: db
        image: mysql
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: cscart
            MYSQL_USER: admin
            MYSQL_PASSWORD: root
        ports:
            - "9906:3306"
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        ports:
            - '8080:80'
        restart: always
        environment:
          PMA_HOST: db
        depends_on:
              - mysql
